#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

# config/routes.yaml

# the "app_lucky_number" route name is not important yet
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

app_home:
  path: /
  controller: App\Controller\ProductController::information

app_product_information:
    path: /produit/information
    controller: App\Controller\ProductController::information
