#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

# config/routes.yaml

app_home:
  path: /
  controller: App\Controller\SearchProductController::searchProduct

app_product_information:
    path: /produit/information/{id}
    controller: App\Controller\ViewProductController::viewProduct
    requirements:
        page: '\d+'

app_product_search:
    path: /produit/recherche
    controller: App\Controller\SearchProductController::searchProduct

app_product_search__ajaxOperators:
    path: /produit/recherche/ajaxOperators
    controller: App\Controller\SearchProductController::getAjaxOperators

#app_product_list:
#    path: /produit/liste
#    controller: App\Controller\ListProductController::listProduct
