#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

# config/routes.yaml

# the "app_lucky_number" route name is not important yet
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

app_home:
  path: /{id}
  controller: App\Controller\ProductController::information
  requirements:
        page: '\d+'

app_product_information:
    path: /produit/information/{id}
    controller: App\Controller\ProductController::information
    requirements:
        page: '\d+'

app_product_search:
    path: /produit/recherche
    controller: App\Controller\ProductController::search
